### ISSUE TITLE
ethra ic mess ado

### ISSUE THREAD

**Issue by kmjayadeep** [moonblade/angular-6-firestore#1]

**Comment by moonblade** [comment]
I couldn't think of a project. So duplicating an old one.

It's to learn shit. Won't be releasing it probably

**Comment by kmjayadeep** [comment]
I'm working on openebs as part of hactoberfest. Seems good

**Comment by moonblade** [comment]
renamed it

**Comment by moonblade** [comment]
> I'm working on openebs as part of hactoberfest. Seems good

Will check it out
